### ISSUE TITLE
delve.set

### ISSUE THREAD

**Issue by chielkunkels** [hughfdjackson/delve#2]
Is there any chance delve would accept a pull request for a `delve.set` function? So basically being able to set a deep value somewhere in an object, making sure objects exist along the way?

**Comment by hughfdjackson** [comment]
@chielkunkels : Years late, I know, but there's a set function in lodash right now.

**Comment by hughfdjackson** [comment]
Here ya go: https://lodash.com/docs#set

**Comment by hughfdjackson** [comment]
Closing this ^^

**Comment by chiel** [comment]
Haha, yea, I've since started using [mout](http://moutjs.com/) myself. This was before lodash supported modular builds, so it made a lot of sense at the time.

Cheers though!
