### ISSUE TITLE
lodash

### ISSUE THREAD

**Issue by callumacrae** [hughfdjackson/delve#4]
Hey!

This library is awesome, and I'm definitely going to continue using it. However, I just discovered that lodash has a [get](https://lodash.com/docs#get) function which does what delve does!

Would it be worth adding a note to the readme that this functionality already exists in lodash? While this library is definitely useful for people who don't already have lodash loaded, a small note would be useful for those of us who have discovered that we're loading two libraries that do the same thing!

**Comment by hughfdjackson** [comment]
@callumacrae: That's a great point :)

**Comment by hughfdjackson** [comment]
https://github.com/hughfdjackson/delve/blob/master/README.markdown#note-for-lodash-users <- do you think this is prominent enough that you would have noticed it?

**Comment by callumacrae** [comment]
@hughfdjackson That's awesome. Apparently your implementation is slightly faster than the lodash version, by the way.
